version: '2'

services:
  telegraf:
    image: telegraf:1.20.3
    container_name: telegraf
    network_mode: host
    volumes:
      - /var/agents/metrics/config/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock:ro
